packages:
  - apps/*
  - packages/*
  - tooling/*
allowBuilds:
  '@tailwindcss/oxide': false
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  prisma-zod-generator: false
  unrs-resolver: true
  vue-demi: true
