/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Swagger
 * Swagger api description
 * OpenAPI spec version: 1.0
 */
import { customFetch } from "../fetcher";
export type UserFindUniqueReqDtoSelect = {
  id?: boolean;
  email?: boolean;
  name?: boolean;
};

export type UserFindUniqueReqDtoWhere = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  email?: string;
};

export interface UserFindUniqueReqDto {
  select?: UserFindUniqueReqDtoSelect;
  where: UserFindUniqueReqDtoWhere;
}

export interface UserFindUniqueResDtoOutput {
  email?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  name?: string;
}

export type userControllerMeResponse200 = {
  data: void;
  status: 200;
};

export type userControllerMeResponseSuccess = userControllerMeResponse200 & {
  headers: Headers;
};
export type userControllerMeResponse = userControllerMeResponseSuccess;

export const getUserControllerMeUrl = () => {
  return `/user/me`;
};

export const userControllerMe = async (
  options?: RequestInit,
): Promise<userControllerMeResponse> => {
  return customFetch<userControllerMeResponse>(getUserControllerMeUrl(), {
    ...options,
    method: "GET",
  });
};

export type userControllerFindUniqueResponseDefault = {
  data: UserFindUniqueResDtoOutput;
  status: number;
};
export type userControllerFindUniqueResponseError =
  userControllerFindUniqueResponseDefault & {
    headers: Headers;
  };

export type userControllerFindUniqueResponse =
  userControllerFindUniqueResponseError;

export const getUserControllerFindUniqueUrl = () => {
  return `/user/find-unique`;
};

export const userControllerFindUnique = async (
  userFindUniqueReqDto: UserFindUniqueReqDto,
  options?: RequestInit,
): Promise<userControllerFindUniqueResponse> => {
  return customFetch<userControllerFindUniqueResponse>(
    getUserControllerFindUniqueUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userFindUniqueReqDto),
    },
  );
};

export type userControllerTelegramAuthResponse200 = {
  data: void;
  status: 200;
};

export type userControllerTelegramAuthResponseSuccess =
  userControllerTelegramAuthResponse200 & {
    headers: Headers;
  };
export type userControllerTelegramAuthResponse =
  userControllerTelegramAuthResponseSuccess;

export const getUserControllerTelegramAuthUrl = () => {
  return `/user/auth/telegram`;
};

export const userControllerTelegramAuth = async (
  options?: RequestInit,
): Promise<userControllerTelegramAuthResponse> => {
  return customFetch<userControllerTelegramAuthResponse>(
    getUserControllerTelegramAuthUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};
