/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Swagger
 * Swagger api description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { unref } from "vue";

import { customFetch } from "../fetcher";
export type UserFindUniqueDtoSelect = {
  id?: boolean;
  email?: boolean;
  name?: boolean;
};

export type UserFindUniqueDtoWhere = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  email?: string;
};

export interface UserFindUniqueDto {
  select?: UserFindUniqueDtoSelect;
  where: UserFindUniqueDtoWhere;
}

export type UserFindUniqueResDtoData = {
  email?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  name?: string;
};

export interface UserFindUniqueResDto {
  success: boolean;
  data?: UserFindUniqueResDtoData;
  error?: string;
}

export type UserFindUniqueResDtoOutputData = {
  email?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  name?: string;
};

export interface UserFindUniqueResDtoOutput {
  success: boolean;
  data?: UserFindUniqueResDtoOutputData;
  error?: string;
}

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type appControllerGetHelloResponse200 = {
  data: void;
  status: 200;
};

export type appControllerGetHelloResponseSuccess =
  appControllerGetHelloResponse200 & {
    headers: Headers;
  };
export type appControllerGetHelloResponse =
  appControllerGetHelloResponseSuccess;

export const getAppControllerGetHelloUrl = () => {
  return `/`;
};

export const appControllerGetHello = async (
  options?: RequestInit,
): Promise<appControllerGetHelloResponse> => {
  return customFetch<appControllerGetHelloResponse>(
    getAppControllerGetHelloUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getAppControllerGetHelloQueryKey = () => {
  return [] as const;
};

export const getAppControllerGetHelloQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetHello>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof appControllerGetHello>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getAppControllerGetHelloQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof appControllerGetHello>>
  > = ({ signal }) => appControllerGetHello({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetHello>>,
    TError,
    TData
  >;
};

export type AppControllerGetHelloQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetHello>>
>;
export type AppControllerGetHelloQueryError = unknown;

export function useAppControllerGetHello<
  TData = Awaited<ReturnType<typeof appControllerGetHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetHello>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAppControllerGetHelloQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export type userControllerFindUniqueResponse200 = {
  data: UserFindUniqueResDto;
  status: 200;
};

export type userControllerFindUniqueResponseDefault = {
  data: UserFindUniqueResDtoOutput;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type userControllerFindUniqueResponseSuccess =
  userControllerFindUniqueResponse200 & {
    headers: Headers;
  };
export type userControllerFindUniqueResponseError =
  userControllerFindUniqueResponseDefault & {
    headers: Headers;
  };

export type userControllerFindUniqueResponse =
  | userControllerFindUniqueResponseSuccess
  | userControllerFindUniqueResponseError;

export const getUserControllerFindUniqueUrl = () => {
  return `/user/find-unique`;
};

export const userControllerFindUnique = async (
  userFindUniqueDto: UserFindUniqueDto,
  options?: RequestInit,
): Promise<userControllerFindUniqueResponse> => {
  return customFetch<userControllerFindUniqueResponse>(
    getUserControllerFindUniqueUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userFindUniqueDto),
    },
  );
};

export const getUserControllerFindUniqueMutationOptions = <
  TError = UserFindUniqueResDtoOutput,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerFindUnique>>,
    TError,
    { data: UserFindUniqueDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerFindUnique>>,
  TError,
  { data: UserFindUniqueDto },
  TContext
> => {
  const mutationKey = ["userControllerFindUnique"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerFindUnique>>,
    { data: UserFindUniqueDto }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerFindUnique(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerFindUniqueMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindUnique>>
>;
export type UserControllerFindUniqueMutationBody = UserFindUniqueDto;
export type UserControllerFindUniqueMutationError = UserFindUniqueResDtoOutput;

export const useUserControllerFindUnique = <
  TError = UserFindUniqueResDtoOutput,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerFindUnique>>,
      TError,
      { data: UserFindUniqueDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof userControllerFindUnique>>,
  TError,
  { data: UserFindUniqueDto },
  TContext
> => {
  return useMutation(
    getUserControllerFindUniqueMutationOptions(options),
    queryClient,
  );
};
